export enum FieldValidationLength {
    TITLE_FIELD_MIN_LENGTH = 5,
   SUMMARY_FIELD_MIN_LENGTH = 1,
    DESCRIPTION_FIELD_MIN_LENGTH = 1,
    FULL_NEWS_FIELD_MIN_LENGTH = 1,
    TITLE_FIELD_MAX_LENGTH = 10,
   SUMMARY_FIELD_MAX_LENGTH = 6,
    DESCRIPTION_FIELD_MAX_LENGTH = 2,
    FULL_NEWS_FIELD_MAX_LENGTH = 6

    // TITLE_FIELD_MIN_LENGTH = 5,
    // SUMMARY_FIELD_MIN_LENGTH = 200,
    //  DESCRIPTION_FIELD_MIN_LENGTH = 100,
    //  FULL_NEWS_FIELD_MIN_LENGTH = 600,
    //  TITLE_FIELD_MAX_LENGTH = 100,
    // SUMMARY_FIELD_MAX_LENGTH = 600,
    //  DESCRIPTION_FIELD_MAX_LENGTH = 200,
    //  FULL_NEWS_FIELD_MAX_LENGTH = 6000
 
}




