export enum FieldValidationLength {

    // Validation for Add News Form
    TITLE_FIELD_MIN_LENGTH = 5,
    SUMMARY_FIELD_MIN_LENGTH = 10,
    DESCRIPTION_FIELD_MIN_LENGTH = 10,
    FULL_NEWS_FIELD_MIN_LENGTH = 10,
    TITLE_FIELD_MAX_LENGTH = 20,
    SUMMARY_FIELD_MAX_LENGTH = 500,
    DESCRIPTION_FIELD_MAX_LENGTH = 200,
    FULL_NEWS_FIELD_MAX_LENGTH = 5000,

    // Validation for Login User Form
    USERNAME_MIN_LENGTH = 5,
    USERNAME_MAX_LENGTH = 20,
    PASSWORD_MIN_LENGTH = 5,
    PASSWORD_MAX_LENGTH = 20,

}




